version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch
    ports:
      - 9200:9200
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: checkdesk-api
    ports:
      - 3000:3000
    links:
      - elasticsearch
      - postgres
      - pender
    volumes:
      - ./checkdesk-api:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
  api-test:
    build: checkdesk-api
    ports:
      - 13000:13000
    links:
      - elasticsearch
      - postgres
      - pender
    volumes:
      - ./checkdesk-api:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13000
  pender:
    build: pender
    ports:
      - 3200:3200
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
  pender-test:
    build: pender
    ports:
      - 13200:13200
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13200
  web:
    build: checkdesk-client
    ports:
      - 3333:3333
    links:
      - api
      - chromedriver
    volumes:
      - ./checkdesk-client:/app
    environment:
      PLATFORM: web
      SERVER_PORT: 3333
  chromedriver:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    environment:
      no_proxy: 'localhost'
      HUB_ENV_no_proxy: 'localhost'
