version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch
    ports:
      - 9200:9200
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: check-api
    ports:
      - 3000:3000
    links:
      - elasticsearch
      - postgres
      - pender
    volumes:
      - ./check-api:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
  api.test:
    build: check-api
    ports:
      - 13000:13000
    links:
      - elasticsearch
      - postgres
    volumes:
      - ./check-api:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13000
  pender:
    build: pender
    ports:
      - 3200:3200
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
  pender.test:
    build: pender
    ports:
      - 13200:13200
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13200
  web:
    build: check-web
    ports:
      - 3333:3333
    links:
      - api
      - chromedriver
    volumes:
      - ./check-web:/app
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
  chromedriver:
    build: chromedriver
    ports:
      - 4444:4444
      - 5900:5900
    environment:
      no_proxy: 'localhost'
      HUB_ENV_no_proxy: 'localhost'
