version: "2.1"
volumes:
  esdata:
  pgdata:
  redis:
  mysql:
networks:
  dev:
services:
  mysql:
    image: mysql:5
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=vframe"
      - "MYSQL_USER=vframe"
      - "MYSQL_PASSWORD=vframe"
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - dev
  elasticsearch:
    image: meedan/elasticsearch:6.3
    environment:
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.disable.jmx=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "esdata:/usr/share/elasticsearch/data"
    networks:
      - dev
  postgres:
    image: postgres:9.6
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql.conf:/etc/postgresql.conf"
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - dev
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    networks:
      - dev
  api:
    build: check-api
    ports:
      - "3000:3000"
      - "3300:3300"
    depends_on:
      - elasticsearch
      - postgres
      - redis
      - pender
    volumes:
      - "./check-api:/app"
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
    networks:
      - dev
  pender:
    build: pender
    shm_size: 1G
    ports:
      - "3200:3200"
      - "9555:9555"
    volumes:
      - "./pender:/app"
    depends_on:
      - redis
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
    networks:
      - dev
  web:
    build: check-web
    ports:
      - "3333:3333"
    depends_on:
      - api
    volumes:
      - "./check-web:/app"
      - "./check-api:/api"
      - "/app/node_modules"
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
      MODE: development
    networks:
      - dev
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - dev
  alegre:
    build: alegre
    ports:
      - "3100:3100"
    volumes:
      - "./alegre:/app"
    depends_on:
      - kibana
      - redis
    environment:
      BOILERPLATE_ENV: dev
      ALEGRE_PORT: 3100
      REDIS_DATABASE: 2
    networks:
      - dev
  vframe:
    build: vframe
    volumes:
      - "./vframe:/root/vframe"
    environment:
      - "DB_HOST=mysql"
      - "DB_NAME=vframe"
      - "DB_USER=vframe"
      - "DB_PASS=vframe"
      - "FLASK_ENV=development"
      - "FLASK_DEBUG=1"
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - dev
