version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch:6.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.disable.jmx=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
      - ./elasticsearch/scripts:/usr/share/elasticsearch/scripts
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: check-api
    ports:
      - 3000:3000
      - 3300:3300
      - 6379:6379
    links:
      - elasticsearch
      - postgres
      - pender
    volumes:
      - ./check-api:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
  pender:
    build: pender
    shm_size: 1G
    ports:
      - 3200:3200
      - 9555:9555
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
  web:
    build: check-web
    ports:
      - 3333:3333
    links:
      - api
    volumes:
      - ./check-web:/app
      - ./check-api:/api
      - /app/node_modules
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
      MODE: development
  mark:
    build: check-mark
    privileged: true
    ports:
      - 8081:8081
    volumes:
      - ./check-mark:/app
      - ./check-api:/api
      - /app/node_modules
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
  bot:
    build: check-bot
    volumes:
      - ./check-bot:/app
      - /app/node_modules
