version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
      - ./elasticsearch/scripts:/usr/share/elasticsearch/scripts
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  api.test:
    build: check-api
    ports:
      - 13000:13000
    links:
      - elasticsearch
      - postgres
      - pender.test
    volumes:
      - ./check-api:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13000
  pender.test:
    build: pender
    ports:
      - 13200:13200
    volumes:
      - ./pender:/app
    environment:
      RAILS_ENV: test
      SERVER_PORT: 13200
  web.test:
    build: check-web
    ports:
      - 13333:13333
    links:
      - api.test
      - chromedriver
    volumes:
      - ./check-web:/app
      - ./check-api:/api
      - /app/node_modules
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 13333
      MODE: test
  mark.test:
    build: check-mark
    links:
      - chromedriver
      - geckodriver
      - api.test
      - web.test
    volumes:
      - ./check-mark:/app
      - ./check-api:/api
      - /app/node_modules
  geckodriver:
    build: geckodriver
    ports:
      - 4445:4444
      - 5901:5900
    volumes:
      - ./check-mark:/app
  chromedriver:
    build: chromedriver
    ports:
      - 4444:4444
      - 5900:5900
    environment:
      no_proxy: 'localhost'
      HUB_ENV_no_proxy: 'localhost'
    volumes:
      - ./check-mark:/app
